### ISSUE TITLE
Incompatible with PHP 8.1

### ISSUE THREAD

**Issue by ghost** [Detsieber/sfe.dico.fibureport#2]
It seems that this lovely extension is not compatible with PHP 8.1.

Tried on WordPress 6.1.1 with CiviCRM 5.55.2 on PHP 8.1.13.

**Comment by Detsieber** [comment]
The compatibility issue is not only about PHP 8.1, but also about CiviCRM 5.60+, when a lot of deprecated function were removed.

However, this extension is only an ugly hack of a civicrm core report (which is based on an old version of civiCRM).
(I can say this so clearly because I am the one who created that ugly hack...) 

I would prefer not to fix the PHP 8.1 and other issues - but instead recreate the report based on SearchKit.

Attached, there is an example for a SearchKit, that might be useful as a replacement.
(this is based on line items instead of financial transactions - but that works in my use cases even better)
[SearchKit_Export_fuer_Buchhaltung.txt](https://github.com/Detsieber/sfe.dico.fibureport/files/13054596/SearchKit_Export_fuer_Buchhaltung.txt)

**Comment by ghost** [comment]
Dear @Detsieber , thank you very much! This Searchkit replacement seems like a smart idea and fulfills my needs 100%. Great!
